### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by tzmfreedom** [tzmfreedom/plis#1]
* [ ] create plist to interactive shell
* [ ] management plist file (peco)
* [ ] reload 
* [ ] create plist from template
